### PR TITLE
Update Cargo.toml add repository

### PR DESCRIPTION
**Pull request by szabgab**
to allow crates.io, rust-digger, and others to link to it

### CODE REVIEW

**Comment by sunero4** [comment]
Thanks a lot for contributing! This is the first time I publish a crate, so I am not very familiar with the various fields in Cargo.toml and how they are used in the package publishing process, so this is much appreciated.
I will merge right away. 
Just out of curiosity, how did you happen to find this repository? :D

**Comment by szabgab** [comment]
I myself am rather new to Rust. I am building the Rust Digger project to collect information about crates and find places where I might be able to help improve them. You will see all of [your crates](https://rust-digger.code-maven.com/users/sunero4) with the collected information. As you publish more and more crates they will be updated there. The site has a list of [crates without repository](https://rust-digger.code-maven.com/no-homepage-no-repo) and [an explanation](https://rust-digger.code-maven.com/about-repository)

Good luck!

**Comment by sunero4** [comment]
Looks like a cool project :) Good luck with that to you as well!

**Comment by szabgab** [comment]
Thank you

**Pull request merged**
